"""P-gp adjudication worksheet and loader — build-plan T13, T15.

Two failure modes shape this module, and both are *silent*:

- **T13 must never clobber (defect 22).** T14 costs a human 60-90 minutes of
  literature work. A worksheet regenerated by a routine ETL re-run that blanked
  those cells would destroy it with no error, so the merge preserves every
  non-empty verdict and refuses to drop a previously-adjudicated key.

- **T15 must distinguish "unadjudicated" from "adjudicated as unknown" (defect
  6).** r1 returned all-'unknown' for a blank worksheet, which looked identical to
  a completed one. An EMPTY cell is an *incomplete* verdict; the literal string
  `unknown` is a *completed* one. They are not the same and must not compare equal.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

#: Worksheet schema. The last four are the human's to fill in T14.
WORKSHEET_COLUMNS = (
    "canonical_inchikey",
    "name",
    "snapshot_label",
    "adjudicated_label",
    "evidence_doi",
    "adjudicated_by",
    "adjudicated_on",
)

#: The columns T13 must never overwrite once non-empty.
HUMAN_OWNED_COLUMNS = (
    "adjudicated_label",
    "evidence_doi",
    "adjudicated_by",
    "adjudicated_on",
)

#: The post-adjudication label domain. 'no' becomes assignable HERE, and only
#: with a citation.
ADJUDICATED_LABELS = frozenset({"yes", "no", "unknown"})

#: A verdict of 'yes' or 'no' is a positive claim and requires attribution.
CITED_LABELS = frozenset({"yes", "no"})


class AdjudicationError(RuntimeError):
    """The adjudication worksheet is incomplete, inconsistent, or unusable."""


def _blank(value: object) -> bool:
    return value is None or pd.isna(value) or str(value).strip() == ""


def _read_worksheet(path: Path) -> pd.DataFrame:
    frame = pd.read_csv(path, dtype=str, keep_default_na=False, na_values=[])
    missing = [c for c in WORKSHEET_COLUMNS if c not in frame.columns]
    if missing:
        raise AdjudicationError(f"{path} is missing column(s): {missing}")
    return frame.loc[:, list(WORKSHEET_COLUMNS)]


def write_adjudication_worksheet(
    labels: pd.Series,
    compounds: pd.DataFrame,
    out: Path,
) -> int:
    """Write a CSV: canonical_inchikey, name, snapshot_label, adjudicated_label,
    evidence_doi, adjudicated_by, adjudicated_on. Last four empty for H.

    NEVER CLOBBERS (defect 22): if `out` exists, merge on canonical_inchikey and
    preserve every non-empty adjudicated_*/evidence_doi cell. Raises if a
    previously-adjudicated key has disappeared from `labels`.
    Raises if any label index is missing from `compounds`.
    Returns row count.
    """
    out = Path(out)

    if "canonical_inchikey" not in compounds.columns:
        raise AdjudicationError("compounds must carry `canonical_inchikey` (T5b)")

    names = (
        compounds.loc[:, ["canonical_inchikey", "name"]]
        .drop_duplicates("canonical_inchikey")
        .set_index("canonical_inchikey")["name"]
    )

    absent = sorted(set(labels.index) - set(names.index))
    if absent:
        raise AdjudicationError(
            f"{len(absent)} labelled key(s) are missing from `compounds`, so no name "
            f"can be rendered for them: {absent[:5]}" + (" ..." if len(absent) > 5 else "")
        )

    fresh = pd.DataFrame(
        {
            "canonical_inchikey": list(labels.index),
            "name": [names[k] for k in labels.index],
            "snapshot_label": list(labels.to_numpy()),
            "adjudicated_label": "",
            "evidence_doi": "",
            "adjudicated_by": "",
            "adjudicated_on": "",
        }
    )

    if out.exists():
        existing = _read_worksheet(out)

        adjudicated = existing[~existing["adjudicated_label"].map(_blank)]
        vanished = sorted(set(adjudicated["canonical_inchikey"]) - set(labels.index))
        if vanished:
            raise AdjudicationError(
                f"{len(vanished)} previously-adjudicated key(s) are absent from the new "
                f"labels: {vanished[:5]}"
                + (" ..." if len(vanished) > 5 else "")
                + ". Refusing to write: this would silently discard human adjudication. "
                "If the snapshot legitimately changed, reconcile deliberately."
            )

        prior = existing.set_index("canonical_inchikey")
        fresh = fresh.set_index("canonical_inchikey")
        for column in HUMAN_OWNED_COLUMNS:
            if column not in prior.columns:
                continue
            carried = prior[column].reindex(fresh.index)
            keep = carried.map(lambda v: not _blank(v))
            fresh.loc[keep.fillna(False), column] = carried[keep.fillna(False)]
        fresh = fresh.reset_index()

    fresh = fresh.loc[:, list(WORKSHEET_COLUMNS)].sort_values(
        "canonical_inchikey", kind="mergesort"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    fresh.to_csv(out, index=False)
    return len(fresh)


def adjudicate_pgp_labels(worksheet: Path, parquet_out: Path | None = None) -> pd.Series:
    """Index: canonical_inchikey. Values: 'yes' | 'no' | 'unknown'.

    Raises if NO row has a non-empty adjudicated_label (a wholly unadjudicated
    worksheet — r1 returned all-'unknown' and looked identical to a completed
    one, defect 6).
    Raises if ANY row has an empty adjudicated_label (partial adjudication).
    Raises if any value is outside {'yes','no','unknown'}.
    Raises if any 'yes'/'no' row lacks evidence_doi or adjudicated_by.
    Raises if the 'yes' group or the 'no' group is empty (defect 24) — the M5
    grouping variable is unusable with only one populated group.

    Also writes data/processed/pgp_labels.parquet, which T17 reads (defect 25).
    """
    worksheet = Path(worksheet)
    frame = _read_worksheet(worksheet)

    filled = ~frame["adjudicated_label"].map(_blank)

    if not filled.any():
        raise AdjudicationError(
            f"{worksheet} is wholly unadjudicated — no row has an adjudicated_label. "
            "An empty cell is an INCOMPLETE verdict, not an 'unknown' one (defect 6); "
            "returning all-'unknown' here would make a blank worksheet indistinguishable "
            "from a completed one."
        )
    if not filled.all():
        blanks = frame.loc[~filled, "canonical_inchikey"].tolist()
        raise AdjudicationError(
            f"{worksheet} is partially adjudicated: {len(blanks)} row(s) have an empty "
            f"adjudicated_label, e.g. {blanks[:5]}. Leave a genuinely uncertain compound "
            "as the explicit string 'unknown'; do not leave the cell blank."
        )

    values = frame["adjudicated_label"].str.strip()
    outside = sorted(set(values) - ADJUDICATED_LABELS)
    if outside:
        raise AdjudicationError(
            f"{worksheet} carries adjudicated_label value(s) outside "
            f"{sorted(ADJUDICATED_LABELS)}: {outside}"
        )

    cited = frame[values.isin(CITED_LABELS)]
    for column in ("evidence_doi", "adjudicated_by"):
        offenders = cited.loc[cited[column].map(_blank), "canonical_inchikey"].tolist()
        if offenders:
            raise AdjudicationError(
                f"{worksheet}: {len(offenders)} row(s) carry a 'yes'/'no' verdict with an "
                f"empty `{column}`, e.g. {offenders[:5]}. A positive or negative claim "
                "without attribution cannot be audited."
            )

    counts = values.value_counts()
    for group in ("yes", "no"):
        if counts.get(group, 0) == 0:
            raise AdjudicationError(
                f"{worksheet} has an empty '{group}' group "
                f"(counts: {counts.to_dict()}). The M5 grouping variable is unusable "
                "with only one populated group (defect 24)."
            )

    series = pd.Series(
        values.to_numpy(), index=frame["canonical_inchikey"], name="adjudicated_label"
    )
    series.index.name = "canonical_inchikey"

    if parquet_out is not None:
        parquet_out = Path(parquet_out)
        parquet_out.parent.mkdir(parents=True, exist_ok=True)
        series.to_frame().to_parquet(parquet_out, engine="pyarrow", version="2.6", compression=None)

    return series


def read_pgp_labels(parquet_path: Path) -> pd.Series:
    """Round-trip counterpart to adjudicate_pgp_labels' parquet write."""
    frame = pd.read_parquet(parquet_path, engine="pyarrow")
    series = frame["adjudicated_label"]
    series.index.name = "canonical_inchikey"
    return series
